---
abstract: 'Extend Plack::Middleware::Debug with MongoDB panels'
author:
  - 'Anton Gerasimov <chim@cpan.org>'
build_requires:
  HTTP::Message: 0
  Plack: 0
  Test::MockObject: 0
  Test::More: 0.98
  Test::Pod: 1.22
  boolean: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Debug-Mongo
no_index:
  directory:
    - t
    - inc
requires:
  MongoDB: 0.502
  Plack: 0
  Plack::Middleware::Debug: 0
  parent: 0
  perl: 5.008009
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/Wu-Wu/Plack-Middleware-Debug-Mongo/issues
  repository: https://github.com/Wu-Wu/Plack-Middleware-Debug-Mongo
version: 0.02
